apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: sma-node-v2
  namespace: smart-apps
spec:
  podSelector:
    matchLabels:
      app: sma-app-v2
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: sma-svc-v2.smart-apps.svc.cluster.local
  logging:
    accessLog:
      file:
        path: "/dev/stdout"
